# Generated by Django 3.1.2 on 2020-11-01 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aut', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projekt',
            name='Bearbeiter',
            field=models.CharField(default='Max Mustermann', max_length=128),
        ),
        migrations.AddField(
            model_name='requirement',
            name='Beschreibung',
            field=models.CharField(default='Bla', max_length=128),
        ),
        migrations.AddField(
            model_name='requirement',
            name='Erstellung',
            field=models.DateTimeField(verbose_name='Erstellung'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='ProjektID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aut.projekt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='Beschreibung',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='ProjektID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aut.projekt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testrun',
            name='Ergebnis',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testrun',
            name='ProjektID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aut.projekt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testrun',
            name='TestCaseID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aut.testcase'),
            preserve_default=False,
        ),
    ]
