# Generated by Django 3.1.2 on 2020-11-01 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aut', '0002_auto_20201101_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projekt',
            name='Bearbeiter',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='Beschreibung',
            field=models.CharField(default='Bla', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='Erstellung',
            field=models.DateTimeField(null=True, verbose_name='Erstellung'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='Name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='ProjektID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aut.projekt'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='Beschreibung',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='Name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='ProjektID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aut.projekt'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='Ergebnis',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='Name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='ProjektID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aut.projekt'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='TestCaseID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aut.testcase'),
        ),
    ]
