# Generated by Django 3.1.2 on 2020-11-01 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aut', '0004_auto_20201101_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='Erstellung',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 11, 1, 0, 0), null=True),
        ),
    ]
