# Generated by Django 3.1.2 on 2020-11-06 16:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aut', '0008_requirement_erstellung'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('Professorennummer', models.UUIDField(default=uuid.uuid4, help_text='Zum Anmelden', primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=128, null=True)),
                ('Passwort', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='Beschreibung',
            new_name='Schritte',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='Name',
            new_name='Vorbedingung',
        ),
        migrations.RemoveField(
            model_name='projekt',
            name='Bearbeiter',
        ),
        migrations.RemoveField(
            model_name='projekt',
            name='id',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='Beschreibung',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='Erstellung',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='ProjektID',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='id',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='ProjektID',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='id',
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='Ergebnis',
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='ProjektID',
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='TestCaseID',
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='id',
        ),
        migrations.AddField(
            model_name='projekt',
            name='ProjektID',
            field=models.UUIDField(default=uuid.uuid4, help_text='Identifikation der Projekte', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='requirement',
            name='Kategorie',
            field=models.CharField(blank=True, choices=[('1', 'Kategorie 1'), ('2', 'Kategorie 2')], help_text='Kategorie des Requirements', max_length=1),
        ),
        migrations.AddField(
            model_name='requirement',
            name='RequirementID',
            field=models.UUIDField(default=uuid.uuid4, help_text='Identifikation der Requirements', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='testcase',
            name='TestCaseID',
            field=models.UUIDField(default=uuid.uuid4, help_text='Identifikation der TestCases', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='testcase',
            name='erwartetesErgebnis',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='tatsaechlichesErgebnis',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='testrun',
            name='Datum_Durchführung',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testrun',
            name='Dauer',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='testrun',
            name='TestCaseID_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aut.testcase'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='TestRunID',
            field=models.UUIDField(default=uuid.uuid4, help_text='Identifikation der TestRuns', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='testrun',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'pass'), ('f', 'fail')], help_text='TestRun Ergebnis', max_length=1),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Matrikelnummer', models.UUIDField(default=uuid.uuid4, help_text='Zum Anmelden', primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=128, null=True)),
                ('Passwort', models.CharField(max_length=128, null=True)),
                ('Gruppennummer_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aut.projekt')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement_TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RequirementID_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aut.requirement')),
                ('TestCaseID_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aut.testcase')),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('ElementID', models.UUIDField(default=uuid.uuid4, help_text='Identifikation der Elements', primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=128, null=True)),
                ('Kommentar', models.CharField(max_length=128, null=True)),
                ('Datum_Erstellung', models.DateTimeField(auto_now_add=True)),
                ('Datum_Aenderung', models.DateTimeField(auto_now=True)),
                ('Matrikelnummer_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aut.student')),
                ('ProjektID_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aut.projekt')),
            ],
        ),
        migrations.AddField(
            model_name='projekt',
            name='Professorennummer_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aut.professor'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='ElementID_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aut.element'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='ElementID_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aut.element'),
        ),
        migrations.AddField(
            model_name='testrun',
            name='ElementID_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aut.element'),
        ),
    ]
