# Generated by Django 3.1.2 on 2020-11-15 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('ElementID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=128, null=True)),
                ('Kommentar', models.CharField(max_length=128, null=True)),
                ('Datum_Erstellung', models.DateTimeField(auto_now_add=True)),
                ('Datum_Aenderung', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('Professorennummer', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=128, null=True)),
                ('Passwort', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('ProjektID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=128, null=True)),
                ('Professorennummer_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aut.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('RequirementID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Kategorie', models.CharField(blank=True, choices=[('1', 'Kategorie 1'), ('2', 'Kategorie 2')], help_text='Kategorie des Requirements', max_length=1)),
                ('ElementID_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aut.element')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('TestCaseID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Vorbedingung', models.CharField(max_length=128, null=True)),
                ('Schritte', models.CharField(max_length=128, null=True)),
                ('erwartetesErgebnis', models.CharField(max_length=128, null=True)),
                ('tatsaechlichesErgebnis', models.CharField(max_length=128, null=True)),
                ('ElementID_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aut.element')),
            ],
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('TestRunID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(blank=True, choices=[('p', 'pass'), ('f', 'fail')], help_text='TestRun Ergebnis', max_length=1)),
                ('Dauer', models.FloatField(null=True)),
                ('Datum_Durchführung', models.DateTimeField(auto_now_add=True)),
                ('ElementID_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aut.element')),
                ('TestCaseID_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aut.testcase')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Matrikelnummer', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=128, null=True)),
                ('Passwort', models.CharField(max_length=128, null=True)),
                ('Gruppennummer_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aut.projekt')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement_TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RequirementID_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aut.requirement')),
                ('TestCaseID_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aut.testcase')),
            ],
        ),
        migrations.AddField(
            model_name='element',
            name='Matrikelnummer_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aut.student'),
        ),
        migrations.AddField(
            model_name='element',
            name='ProjektID_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aut.projekt'),
        ),
    ]
