# Generated by Django 3.1.2 on 2020-11-16 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aut', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='Matrikelnummer_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aut.student'),
        ),
        migrations.AlterField(
            model_name='element',
            name='ProjektID_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aut.projekt'),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='Professorennummer_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aut.professor'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='ElementID_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aut.element'),
        ),
        migrations.AlterField(
            model_name='requirement_testcase',
            name='RequirementID_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aut.requirement'),
        ),
        migrations.AlterField(
            model_name='requirement_testcase',
            name='TestCaseID_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aut.testcase'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Gruppennummer_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aut.projekt'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='ElementID_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aut.element'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='ElementID_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aut.element'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='TestCaseID_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aut.testcase'),
        ),
    ]
