# Generated by Django 3.1.2 on 2020-11-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aut', '0002_auto_20201116_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='Name',
            field=models.CharField(help_text='Name des Professors', max_length=128, null=True),
        ),
    ]
