# Generated by Django 3.1.2 on 2020-11-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aut', '0003_auto_20201101_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='Erstellung',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
