# Generated by Django 3.1.2 on 2020-11-28 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aut', '0004_requirement_ersteller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirement',
            options={'permissions': (('can_mark_category', 'Set a Category'),)},
        ),
    ]
