# Generated by Django 3.1.2 on 2020-11-28 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aut', '0005_auto_20201128_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirement',
            options={},
        ),
    ]
