# Generated by Django 3.1.2 on 2020-11-01 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aut', '0005_auto_20201101_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='Erstellung',
        ),
    ]
