# Generated by Django 3.1.2 on 2020-11-01 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aut', '0006_remove_requirement_erstellung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projekt',
            name='Name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='ProjektID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aut.projekt'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='ProjektID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aut.projekt'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='ProjektID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aut.projekt'),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='TestCaseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aut.testcase'),
        ),
    ]
