# Generated by Django 3.1.2 on 2020-11-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aut', '0007_auto_20201101_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='Erstellung',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
