# Generated by Django 3.1.2 on 2020-11-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aut', '0009_auto_20201106_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projekt',
            name='ProjektID',
            field=models.CharField(help_text='Identifikation der Projekte', max_length=128, primary_key=True, serialize=False),
        ),
    ]
